import type { MDXComponents } from "mdx/types";
import {
  Accordion,
  Alert,
  AlertDialog,
  Avatar,
  AvatarGroup,
  Badge,
  Box,
  Breadcrumb,
  Button,
  ButtonGroup,
  Code,
  Checkbox,
  CheckboxGroup,
  CloseButton,
  Collapse,
  ControlBox,
  CircularProgress,
  Divider,
  Drawer,
  Editable,
  Flex,
  FormControl,
  FormHelperText,
  FormLabel,
  FormErrorMessage,
  Grid,
  Heading,
  Icon,
  IconButton,
  Image,
  Input,
  InputAddon,
  InputGroup,
  Kbd,
  Link,
  List,
  Stack,
  SimpleGrid,
  Menu,
  Modal,
  NumberInput,
  Portal,
  Popover,
  Progress,
  Radio,
  RadioGroup,
  Select,
  Skeleton,
  Slider,
  Spinner,
  Stat,
  Switch,
  Tabs,
  Tag,
  Text,
  Textarea,
  Tooltip,
  VisuallyHidden,
  ListItem,
  Table,
  UnorderedList,
  OrderedList,
} from "@chakra-ui/react";
import { DataTable, DataTableHeader } from "@saas-ui/react";
import { MDXProvider } from "@mdx-js/react";
import { Em } from "components/typography";

const yspace = 6;

export const mdxComponents = {
  h1: (props) => <Heading as="h1" mt={yspace} {...props} />,
  h2: (props) => <Heading as="h2" mt={yspace} {...props} />,
  h3: (props) => <Heading as="h3" {...props} />,
  h4: (props) => <Heading as="h4" {...props} />,
  p: (props) => <Text my={yspace} as="p" {...props} />,
  a: (props) => <Link {...props} />,
  ul: (props) => <UnorderedList as="ul" {...props} />,
  ol: (props) => <OrderedList as="ol" {...props} />,
  li: (props) => <ListItem as="li" mb={2} {...props} />,
  strong: (props) => <Em {...props} />,
  em: (props) => <Em as="em" {...props} />,
  pre: (props) => <Code as="pre" {...props} />,
  code: (props) => <Code as="code" {...props} />,
  blockquote: (props) => <blockquote {...props} />,
  hr: (props) => <Divider {...props} />,
  // eslint-disable-next-line jsx-a11y/alt-text
  img: (props) => <Image {...props} />,
  table: (props) => <DataTable as="table" {...props} />,
  thead: (props) => <DataTableHeader as="thead" {...props} />,
  tbody: (props) => <Box as="tbody" {...props} />,
  tfoot: (props) => <Box as="tfoot" {...props} />,
  tr: (props) => <Box as="tr" {...props} />,
  th: (props) => <Box as="th" {...props} />,
  td: (props) => <Box as="td" {...props} />,
  caption: (props) => <Box as="caption" {...props} />,
  div: (props) => <Box as="div" {...props} />,
  span: (props) => <Box as="span" {...props} />,
  br: (props) => <Box as="br" my={4} {...props} />,
};

export const MdxProvider = ({ children }) => {
  return <MDXProvider components={mdxComponents}>{children}</MDXProvider>;
};

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return mdxComponents;
}
